
# PostgreSQL 리플리케이션 설정을 위한 ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config  # ConfigMap 이름
  namespace: psql        # 네임스페이스 지정
data:
  postgresql.conf: |      # PostgreSQL 설정 파일 (postgresql.conf)
    listen_addresses = '*'
    wal_level = replica
    max_wal_senders = 10
    wal_keep_segments = 10
    hot_standby = on
  #모든 IP에서 연결 허용
  #리플리케이션을 위한 WAL 로그 수준 설정
  #WAL 전송 프로세스의 최대 개수
  #리플리케이션을 위한 WAL 세그먼트 보관 수
  #팔로워(복제본)에서 읽기 전용 모드 허용
  pg_hba.conf: |           # PostgreSQL 호스트 기반 인증 파일 (pg_hba.conf)
    host replication all 0.0.0.0/0 md5    
  # 모든 IP에서 리플리케이션 허용, MD5 인증 사용
  POSTGRES_DB: postgresdb   # POSTGRES_DB 추가 (데이터베이스 이름)
  POSTGRES_USER: admin      # POSTGRES_USER 추가 (사용자 이름)

---
# PersistentVolumeClaim (PVC) 설정
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-claim          # PVC 이름
  namespace: psql              # 네임스페이스 지정
spec:
  accessModes:
    - ReadWriteOnce            # 하나의 노드에서 읽기/쓰기를 허용
  resources:
    requests:
      storage: 10Gi            # 요청된 스토리지 크기 (10GiB)
  storageClassName: standard    # 사용하려는 스토리지 클래스

---
# PostgreSQL StatefulSet 설정
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres               # StatefulSet 이름
  namespace: psql              # 네임스페이스 지정
spec:
  serviceName: postgres        # StatefulSet에서 사용하는 서비스 이름
  replicas: 3                  # 복제본 수 (리더 1개, 팔로워 2개)
  selector:
    matchLabels:
      app: postgres            # 파드 레이블 지정
  template:
    metadata:
      labels:
        app: postgres          # 파드 레이블
    spec:
      containers:
        - name: postgres       # 컨테이너 이름
          image: postgres:latest  # 사용할 PostgreSQL 이미지
          imagePullPolicy: "IfNotPresent" # 이미지가 없을 때만 풀링
          ports:
            - containerPort: 5432       # PostgreSQL 포트
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:        # ConfigMap에서 값을 가져옴
                  name: postgres-config  # ConfigMap 이름
                  key: POSTGRES_DB       # 데이터베이스 이름 키
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:        # ConfigMap에서 값을 가져옴
                  name: postgres-config
                  key: POSTGRES_USER     # 사용자 이름 키
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:           # Secret에서 값을 가져옴
                  name: postgres-secret  # Secret 이름
                  key: POSTGRES_PASSWORD # 비밀번호 키
          volumeMounts:
            - name: data                # 볼륨 마운트 (데이터 저장)
              mountPath: /var/lib/postgresql/data
            - name: config-volume        # PostgreSQL 설정 파일 마운트
              mountPath: /etc/postgresql
      volumes:
        - name: data                    # PVC로부터 볼륨 생성
          persistentVolumeClaim:
            claimName: example-claim     # PVC 이름
        - name: config-volume            # ConfigMap으로부터 볼륨 생성
          configMap:
            name: postgres-config        # ConfigMap 이름
            items:
              - key: postgresql.conf     # postgresql.conf 파일
                path: postgresql.conf    # 마운트할 경로
              - key: pg_hba.conf         # pg_hba.conf 파일
                path: pg_hba.conf        # 마운트할 경로

---
# PostgreSQL에 연결하기 위한 서비스 설정
apiVersion: v1
kind: Service
metadata:
  name: postgres                  # 서비스 이름
  namespace: psql                 # 네임스페이스 지정
  labels:
    app: postgres                 # 서비스 레이블
spec:
  selector:
    app: postgres                 # 해당 레이블을 가진 파드 선택
  ports:
    - protocol: TCP
      name: postgres
      port: 5432                  # PostgreSQL 기본 포트
      targetPort: 5432             # 파드에서 사용하는 포트

---
# PostgreSQL 비밀번호 및 리플리케이션 비밀번호를 위한 Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret           # Secret 이름
  namespace: psql                 # 네임스페이스 지정
type: Opaque                      # 암호화된 Secret 타입
data:
  POSTGRES_PASSWORD: cHJpbWFyeXBhc3N3b3Jk  # base64 인코딩된 primarypassword
